name: Stoch Lab
url: "stochlab.github.io"
baseurl: ""
base: ""

exclude: [bibble, README.md, Makefile, screenshot.png]

# Base pathname for links. Uncomment this to build for deployment.
# base: /rexlab-website

# colorize code snippets with the rouge module
highlighter: rouge

# The path structure for blog posts.
permalink: /research/stoch/blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
  - key: staff
    name: Staff
  # - key: postdoc
  #   name: Researchers
  - key: phd 
    name: PhD Students
  - key: masters
    name: Masters Students
  - key: fellow
    name: Visiting Students
  - key: intern
    name: Interns
  - key: intern-alum
    name: Past Interns/Visiting Students/ Staff
  # - key: collab
  #   name: Collaborators
  - key: alum
    name: Alumni

# Number of news stories on the front page.
front_page_news: 4

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /people.html
  - title: Research
    link: /research.html
  - title: Publications
    link: /publications.html
  - title: Code
    link: /code.html
#  - title: Calendar
#    link: /calendar.html
  - title: YouTube
    link: https://www.youtube.com/channel/UC4SBmq_fVgzyaqHHyITkSjA
  - title: Join Us
    link: /join.html
theme: jekyll-theme-cayman
